# Generated by Django 3.2 on 2021-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('major', models.CharField(choices=[('IT', 'I.T.'), ('PHY', 'Physics'), ('CHM', 'Chemistry'), ('ST', 'Statistics'), ('MKT', 'Marketing')], max_length=500)),
                ('year', models.CharField(choices=[('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=500)),
                ('GPA', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
