# Generated by Django 3.2 on 2021-05-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursename', models.CharField(max_length=500)),
                ('coursetitle', models.CharField(max_length=500)),
                ('sectioncode', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=500)),
                ('instructorname', models.CharField(max_length=500)),
            ],
        ),
    ]
