# Generated by Django 3.2 on 2021-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_coursedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentenrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('studentid', models.IntegerField()),
            ],
        ),
    ]
